server:
  port: 8888
  servlet:
    context-path: /api
  error:
    include-message: always

spring:
  main:
    allow-circular-references: true
  application:
    name: user-service
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/demo_user?useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true